Commit for v700
InMobi/sdk-sample-code-android pull request #10
Opened 2017-09-18 10:38 UTC by SwagatoMondal

Commit for v700

2017-09-19 10:39 UTC, amit-prabhudesai requested changes
Please check the notes. Also, I suppose the recommended Google Play Services version should still be 8.4.0? This was changed in the 6.2.4 update, but should be set to the version that QA has certified with.

2017-09-19 10:39 UTC, amit-prabhudesai commented on README.md
> +InMobi SDK v7.0.0 for Android introduces the ability to monetize the lock screen.
The description here needs update.

2017-09-19 10:39 UTC, amit-prabhudesai commented on samples/nativeSample/build.gradle
> +    compile 'com.android.support.constraint:constraint-layout:1.0.2'
Are we actually using `ConstraintLayout`s?

2017-09-19 10:39 UTC, amit-prabhudesai commented on samples/nativeSample/src/main/java/com/inmobi/nativead/PlacementId.java
> +}
Nit: No newline at end-of-file.

2017-09-19 10:39 UTC, amit-prabhudesai commented on samples/nativeSample/src/main/java/com/inmobi/nativead/sample/singlestrand/SingleStrandFragment.java
> +public class SingleStrandFragment extends Fragment
We no longer have "strands", so the class name and the class-level Javadoc needs to  change.

2017-09-19 12:21 UTC, SwagatoMondal commented
@amit-prabhudesai Added changes as per review comments. Please review.

2017-09-21 07:07 UTC, amit-prabhudesai approved these changes
Looks good.

2017-09-21 07:28 UTC, merged