Support for SDK v916
InMobi/sdk-sample-code-android pull request #74
Opened 2021-02-18 07:09 UTC by manoj897

2021-02-18 07:19 UTC, RajSuvariya-InMobi requested changes

2021-02-18 07:19 UTC, RajSuvariya-InMobi commented on samples/bannerSample/build.gradle
>      implementation 'com.google.android.gms:play-services-location:16.0.0'
Let's use project-level Gradle to maintain dependency versions, also match the versions with supported deps versions

2021-02-19 09:40 UTC, RajSuvariya-InMobi requested changes

2021-02-19 09:40 UTC, RajSuvariya-InMobi commented on build.gradle
> +    recyclerview = "1.0.0"
We have "1.1.0"  in unified-sdk

2021-02-19 10:11 UTC, im-lakshya commented on build.gradle
> +    androidMinSdkVersion = 16
SDK minimum support is 15, but it is 16 ?

2021-02-19 11:21 UTC, im-lakshya commented
InMobiSDK.aar is deleted, but we replace it with new version everytime

2021-02-22 05:32 UTC, RajSuvariya-InMobi approved these changes

2021-02-23 17:01 UTC, manoj897 commented
> InMobiSDK.aar is deleted, but we replace it with new version everytime

I can see that aar file is checked in

2021-02-23 17:05 UTC, im-lakshya commented
> I can see that aar file is checked in

My bad, I've reviewed it commit wise and in there it was showing it as deleted but when reviewed accumulated file changes it is showing as updated.

2021-02-23 17:05 UTC, im-lakshya approved these changes

2021-02-23 17:18 UTC, merged